/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_application;

/**
 *
 * @author kanniyappan.s
 */
import javax.swing.*;
import java.sql.*;
import DB.JDBC;
import Regex.CHECK;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class Agents extends javax.swing.JFrame {

    /**
     * Creates new form Agents
     */
    public Agents() {
        initComponents();
        tab();
        select();
    }
    private boolean isNumber(String Number){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select count(*) from agents where phonenumber=?")){
              pst.setString(1,Number);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){
                 return rs.getInt(1)>0;
              }
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          return false;
    }
    private boolean isNumberOwner(String Id,String Number){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select count(*) from agents where id=? and phonenumber=?")){
              pst.setString(1,Id);
              pst.setString(2,Number);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){
                 return rs.getInt(1)>0;
              }
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          return false;
    }
     private boolean isEmail(String Email){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select count(*) from agents where email=?")){
              pst.setString(1,Email);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){
                 return rs.getInt(1)>0;
              }
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          return false;
    }
     private boolean isEmailOwner(String Id,String Email){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select count(*) from agents where id=? and email=?")){
              pst.setString(1,Id);
              pst.setString(2,Email);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){
                 return rs.getInt(1)>0;
              }
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          return false;
    }
    public void tab(){
       try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_agents_getall")){
         ResultSet rs=pst.executeQuery();
         DefaultTableModel m=(DefaultTableModel)table.getModel();
         m.setRowCount(0);
         while(rs.next()){
            m.addRow(new Object[]{rs.getString("id"),rs.getString("name"),rs.getString("password"),rs.getInt("age"),rs.getString("gender"),rs.getString("address"),
                     rs.getString("phonenumber"),rs.getString("email")
            });
         }
       }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
     }
  
    public void clear(){
       id.setSelectedItem("");
       name.setText("");
       password.setText("");
       age.setText("");
       gender.setSelectedItem("SELECT GENDER");
       address.setText("");
       phonenumber.setText("");
       emailid.setText("");
    }
    public void select(){
      try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_login_getall")){
         ResultSet rs=pst.executeQuery();
         id.removeAllItems();
         id.addItem("AGENT ID");
         while(rs.next()){
            String AID=rs.getString("id");
            id.addItem(AID);
        }
      }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        gender = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        close = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        show = new javax.swing.JCheckBox();
        id = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENTS ");
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Agets-Mini.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("AGENTS MANIPULATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "PASSWORD", "AGE", "GENDER", "ADDRESS", "PHONENUMBER", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(40);
        table.setSelectionBackground(new java.awt.Color(51, 0, 51));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 988, 192));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGENTS ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 118, 149, 36));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 172, 149, 36));

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 172, 207, 36));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 226, 149, 36));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AGE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 280, 149, 36));

        age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 280, 207, 36));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GENDER");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 149, 36));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADDRESS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 149, 36));

        address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 207, 36));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PHONE NUMBER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, 36));

        phonenumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phonenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenumberFocusLost(evt);
            }
        });
        getContentPane().add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 207, 36));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EMAIL ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 149, 36));

        emailid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailidFocusLost(evt);
            }
        });
        getContentPane().add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 207, 36));

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 226, 207, 36));

        gender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GENDER", "MALE", "FEMALE", "OTHERS" }));
        gender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                genderFocusLost(evt);
            }
        });
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 207, 36));

        add.setBackground(new java.awt.Color(0, 0, 102));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 328, 154, 36));

        edit.setBackground(new java.awt.Color(102, 102, 102));
        edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 0));
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 328, 146, 36));

        delete.setBackground(new java.awt.Color(255, 51, 51));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 328, 132, 36));

        close.setBackground(new java.awt.Color(153, 0, 0));
        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 568, 157, 45));

        clear.setBackground(new java.awt.Color(255, 153, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 569, 150, 43));

        show.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 226, 103, 36));

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 118, 207, 38));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("YOU CAN'T CHANGE NAME AND PASSWORD");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 616, 530, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Agents().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String Id=(String)id.getSelectedItem();
        String Name=name.getText();
        String Password=password.getText();
        int Age=Integer.parseInt(age.getText());
        String Gender=(String)gender.getSelectedItem();
        String Address=address.getText();
        String Number=phonenumber.getText();
        String Email=emailid.getText();
        String Text="SELECT GENDER";
        if(Gender.equals(Text)){
          JOptionPane.showMessageDialog(this,"Please Select The Gender...");
          return;
        }
         if(isNumber(Number)){
              JOptionPane.showMessageDialog(this,"This Number Already Exits. Please Enter Another Phone Number");
              return;
           }
           if(isEmail(Email)){
              JOptionPane.showMessageDialog(this,"This Email Id Already Exits. Please Enter Another Email Id");
              return;
           }
        if(!Id.isEmpty() && !Name.isEmpty() && !Password.isEmpty() && !Address.isEmpty() && !Number.isEmpty() && !Email.isEmpty())
        {
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_agents_insert ?,?,?,?,?,?,?,?")){
               pst.setString(1,Id);
               pst.setString(2,Name);
               pst.setString(3,Password);
               pst.setInt(4,Age);
               pst.setString(5,Gender);
               pst.setString(6,Address);
               pst.setString(7,Number);
               pst.setString(8,Email);
               int a=pst.executeUpdate();
              if(a>0){
                   
                 JOptionPane.showMessageDialog(this,"Agents Details Added.....");
                 clear();
                 tab();
                 
                }else{JOptionPane.showMessageDialog(this,"Failed For Agents Details Add Process..");}
           }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
        }else{JOptionPane.showMessageDialog(this,"Please Enter All The Fields....");}
    }//GEN-LAST:event_addActionPerformed

    private void phonenumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumberFocusLost
        // TODO add your handling code here:
        String Number=phonenumber.getText();
        if(!CHECK.isValidPhone(Number)){
            JOptionPane.showMessageDialog(this,"Please Enter Valid Phone Number In 10 Digit");
            return;
        }
    }//GEN-LAST:event_phonenumberFocusLost

    private void emailidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailidFocusLost
        // TODO add your handling code here:
        String Email=emailid.getText();
        if(!CHECK.isValidEmail(Email)){
               JOptionPane.showMessageDialog(this,"Please Enter Valid Email Id");
               return;
        }
    }//GEN-LAST:event_emailidFocusLost

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
         String Id=(String)id.getSelectedItem();
        String Name=name.getText();
        String Password=password.getText();
        int Age=Integer.parseInt(age.getText());
        String Gender=(String)gender.getSelectedItem();
        String Address=address.getText();
        String Number=phonenumber.getText();
        String Email=emailid.getText();
        if(!isNumberOwner(Id,Number)&& isNumber(Number)){
              JOptionPane.showMessageDialog(this,"This Number Already Exits. Please Enter Another Phone Number");
              return;
           }
           if(!isEmailOwner(Id,Email)&& isEmail(Email)){
              JOptionPane.showMessageDialog(this,"This Email Id Already Exits. Please Enter Another Email Id");
              return;
           }
        if(!Id.isEmpty())
        {
           try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_agents_update ?,?,?,?,?,?,?,?")){
               pst.setString(1,Id);
               pst.setString(2,Name);
               pst.setString(3,Password);
               pst.setInt(4, Age);
               pst.setString(5,Gender);
               pst.setString(6,Address);
               pst.setString(7,Number);
               pst.setString(8,Email);
               int a=pst.executeUpdate();
              if(a>0){
                  
                 JOptionPane.showMessageDialog(this,"Agents Details Edited.....");
                 clear();
                 tab();
                 
              }else{JOptionPane.showMessageDialog(this,"Failed For Agents Details Edit Process..");}
           }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
        }else{JOptionPane.showMessageDialog(this,"Please Select Agent Id In The Table");}
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String Id=(String)id.getSelectedItem();
        int a=JOptionPane.showConfirmDialog(this,"DO YOU WANT DELETE THIS AHENT ?","SELECT",JOptionPane.YES_NO_OPTION);
        if(!Id.isEmpty()){
              if(a==0){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_agents_delete ?");
                  PreparedStatement st=c.prepareStatement("sp_login_delete ?")){
              pst.setString(1,Id);
              st.setString(1,Id);
              pst.executeUpdate();
              st.executeUpdate();
              JOptionPane.showMessageDialog(this,"This Agent Was Deleted.....");
              clear();
              tab();
              
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
            }
        }else{JOptionPane.showMessageDialog(this,"Please Select The Agent Id In The Table");}
    }//GEN-LAST:event_deleteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        edit.setEnabled(false);
        delete.setEnabled(false);
        name.setEditable(false);
        password.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index=table.getSelectedRow();
        TableModel m=table.getModel();
        id.setSelectedItem(m.getValueAt(index,0).toString());
        name.setText(m.getValueAt(index,1).toString());
        password.setText(m.getValueAt(index,2).toString());
        age.setText(m.getValueAt(index,3).toString());
        gender.setSelectedItem(m.getValueAt(index,4).toString());
        address.setText(m.getValueAt(index,5).toString());
        phonenumber.setText(m.getValueAt(index,6).toString());
        emailid.setText(m.getValueAt(index,7).toString());
        
        add.setEnabled(false);
        edit.setEnabled(true);
        delete.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void genderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genderFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_genderFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        String Password=password.getText();
        if(!CHECK.isValidPass(Password)){
          JOptionPane.showMessageDialog(this,"Minimum 4 Character Include UpperCase,LowerCase,Special Character");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        if(show.isSelected()){
           password.setEchoChar((char)0);
         }else{
           password.setEchoChar('*');
         }
        
    }//GEN-LAST:event_showActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
        String Id=(String)id.getSelectedItem();
        try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_login_getById ?")){
         pst.setString(1,Id);
         ResultSet rs=pst.executeQuery();
         if(rs.next()){
          name.setText(rs.getString("name"));
          password.setText(rs.getString("password"));
         }
      }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField emailid;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JCheckBox show;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
