/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_application;

/**
 *
 * @author kanniyappan.s
 */
import javax.swing.*;
import java.sql.*;
import DB.JDBC;
import java.awt.event.ActionEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        tab();
        bid.setText(bill_no());
        time();
    }
    public void tab(){
    try(Connection c=JDBC.con();PreparedStatement st=c.prepareStatement("sp_medicine_getall")){
        ResultSet rs=st.executeQuery();
        DefaultTableModel m=(DefaultTableModel)table.getModel();
        m.setRowCount(0);
        while(rs.next()){
          m.addRow(new Object[]{rs.getString("id"),rs.getString("name"),rs.getInt("quantity"),rs.getString("price"),rs.getString("manufacturedate"),rs.getString("expiredate"),rs.getString(("companyname"))});
        }
    }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
    }
    public void time(){
      Timer timer=new Timer(1000,(ActionEvent e)->{
      Date d=new Date();
      String date1=new SimpleDateFormat("dd-MM-yyyy").format(d);
      String time1=new SimpleDateFormat("hh-mm-ss a").format(new Date());
      date.setText(date1);
      time.setText(time1);
      });
      timer.start();
      setVisible(true);
    }
    public String bill_no(){
          String res="";
          String R;
          String code="BINO";
          Random rd=new Random();
          String arr[]={"0","1","2","3","4","5","6","7","8","9"};
          for(int i=0;i<=6;i++){
              int b=rd.nextInt(arr.length);
              res=res+arr[b];
          }
        R=code+res;
        return R;
    }
    SimpleDateFormat dt=new SimpleDateFormat("yyyy-MM-dd");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        billtable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        billdetails = new javax.swing.JButton();
        bill = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        quan = new javax.swing.JTextField();
        go = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BILL");
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bill-Mini.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("MEDICINE BILL");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("DATE :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("TIME :");

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jLabel1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINE ID", "MEDICINE NAME", "STOCK", "PRICE", "MANUFACTURE DATE", "EXPIRE DATE", "COMPANY NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(40);
        table.setSelectionBackground(new java.awt.Color(51, 0, 0));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 462, 1188, 185));

        reset.setBackground(new java.awt.Color(204, 204, 0));
        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 102));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 690, 139, 35));

        close.setBackground(new java.awt.Color(102, 0, 0));
        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 690, 135, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("BILL ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, 154, 41));

        bid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 92, 203, 41));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("MED.NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, 154, 41));

        mname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 151, 203, 41));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("STOCK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, 154, 41));

        stock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 210, 203, 41));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("PRICE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 263, 154, 41));

        price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 263, 203, 41));

        add.setBackground(new java.awt.Color(0, 102, 51));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD ");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 363, 152, 40));

        clear.setBackground(new java.awt.Color(255, 204, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 51, 51));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 363, 141, 40));

        billtable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        billtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BILL ID", "MEDICINE NAME", "QUANTITY", "PRICE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billtable.setRowHeight(40);
        billtable.setSelectionBackground(new java.awt.Color(51, 0, 51));
        billtable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        billtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(billtable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 127, 741, 183));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("TOTAL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 317, 62, 39));

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 317, 96, 39));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("PAID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 317, 56, 39));

        paid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 317, 93, 39));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("BALANCE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 317, 93, 39));

        balance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 317, 84, 39));

        print.setBackground(new java.awt.Color(0, 0, 102));
        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 374, 200, -1));

        billdetails.setBackground(new java.awt.Color(0, 255, 204));
        billdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        billdetails.setForeground(new java.awt.Color(102, 0, 0));
        billdetails.setText("BILL DETAILS");
        billdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(billdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 374, 201, -1));

        bill.setBackground(new java.awt.Color(0, 102, 102));
        bill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bill.setForeground(new java.awt.Color(204, 204, 0));
        bill.setText("GET BILL");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        getContentPane().add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 374, 200, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setText("REQ.QUANTITY");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 316, 154, 41));

        quan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 316, 203, 41));

        go.setBackground(new java.awt.Color(153, 255, 0));
        go.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        go.setForeground(new java.awt.Color(51, 0, 153));
        go.setText("GO");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        getContentPane().add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 151, -1, 41));

        remove.setBackground(new java.awt.Color(102, 51, 0));
        remove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073, 317, -1, 39));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 0));
        jLabel13.setText("BILL TABLE");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 93, 148, 28));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 0));
        jLabel14.setText("STOCK TABLE DETAILS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 421, -1, -1));

        pay.setBackground(new java.awt.Color(0, 51, 51));
        pay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pay.setForeground(new java.awt.Color(204, 204, 0));
        pay.setText("PAY");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 316, 84, 39));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Bill().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        mname.setText("");
        stock.setText("");
        price.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        bid.setEditable(false);
        stock.setEditable(false);
        price.setEditable(false);       
        bill.setEnabled(false);
        print.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        String Name=mname.getText();
        if(!Name.isEmpty()){
            try(Connection c=JDBC.con();PreparedStatement st=c.prepareStatement("select * from medicine where name=?")){
                st.setString(1,Name);
                ResultSet rs=st.executeQuery();
                if(rs.next()){
                   String Stock=rs.getString("quantity");
                   String Price=rs.getString("price");
                   stock.setText(Stock);
                   price.setText(Price);
                }
            }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
        }else{JOptionPane.showMessageDialog(this,"Please Enter Medicine Name");}
    }//GEN-LAST:event_goActionPerformed
double finaltotal=0;
int q=0;
double p=0;
double tot=0;
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String Name=mname.getText();
        String Quantity=quan.getText();
        if(!Quantity.isEmpty() && !Name.isEmpty()){
               int Stock=Integer.parseInt(stock.getText());
        int Quan=Integer.parseInt(quan.getText());
        if(Quan>Stock){
              JOptionPane.showMessageDialog(this,"WE DON'T HAVE IN THIS MANY MEDICINE ...");
              return;
           }else{try(Connection c=JDBC.con();
                   PreparedStatement pst=c.prepareStatement("sp_medicine_check ?,?");
                   PreparedStatement st=c.prepareStatement("select * from medicine where name=?")){
               pst.setString(1,Name);
               pst.setInt(2,Quan);
               int a=pst.executeUpdate();
               if(a>0){JOptionPane.showMessageDialog(this,"THIS MEDICINE STOCK UPDATED IN STORE AREA....");}
               pst.close();
               
           q=Integer.parseInt(quan.getText());
           p=Double.parseDouble(price.getText());
           tot=p*q;
           finaltotal=finaltotal+tot;
           DefaultTableModel m=(DefaultTableModel)billtable.getModel();
           m.addRow(new Object[]{bid.getText(),mname.getText(),q,p,tot});
           String Total=String.valueOf(finaltotal);
           total.setText(Total);
           total.setEditable(false);
           quan.setText("");
               st.setString(1,Name);
               ResultSet rs=st.executeQuery();
               if(rs.next()){
                   mname.setText(rs.getString("name"));
                   stock.setText(rs.getString("quantity"));
                   price.setText(rs.getString("price"));
                }
               st.close();
           }catch(Exception e){JOptionPane.showMessageDialog(this,e);}         
        }
        bill.setEnabled(true);
        print.setEnabled(true);
        billdetails.setEnabled(true);
     }else{JOptionPane.showMessageDialog(this,"Please Enter Required Quantity And Medicine Name....");}
    }//GEN-LAST:event_addActionPerformed
 int row=0;
 double tot1;
    private void billtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billtableMouseClicked
        // TODO add your handling code here:
            row=billtable.rowAtPoint(evt.getPoint());
            tot1=(double)billtable.getValueAt(row,4);
    }//GEN-LAST:event_billtableMouseClicked

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m=(DefaultTableModel)billtable.getModel();
        int index=billtable.getSelectedRow();
        if(index==-1){
           JOptionPane.showMessageDialog(this,"Please Select The Row Bill table For Removed  Medicine In Bill..");
           return;
       }
        if(billtable.getSelectedRowCount()==1){
                String MedName=billtable.getValueAt(index,1).toString();
                int Quan=Integer.parseInt(billtable.getValueAt(index,2).toString());
                m.removeRow(index);
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_medicine_add ?,?");
          PreparedStatement st=c.prepareStatement("select * from medicine where name=?")){
                pst.setString(1,MedName);
                pst.setInt(2,Quan);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"THIS MEDICIENE REMOVE FROM BILL TABLE.....");
                pst.close();
              
                finaltotal=finaltotal-tot1;
                String T=String.valueOf(finaltotal);
                total.setText(T);
                total.setEditable(false);
               
                st.setString(1,MedName);
                ResultSet rs=st.executeQuery();
                if(rs.next())
                {
                  mname.setText(rs.getString("name"));
                  stock.setText(rs.getString("quantity"));
                  price.setText((rs.getString("price")));
                }
                quan.setText("");
            }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
        }
    }//GEN-LAST:event_removeActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
       String Paid=paid.getText();
       if(!Paid.isEmpty()){
          double Final=Double.parseDouble(total.getText());
          double Pay=Double.parseDouble(Paid);
          double Balance;
          if(Pay>=Final){
               Balance=Pay-Final;
               String Bal=String.valueOf(Balance);
               balance.setText(Bal);
          }else{JOptionPane.showMessageDialog(this,"Please Give A Valid Amount.....");}
         balance.setEditable(false);
       }else{JOptionPane.showMessageDialog(this,"Please Give A Your Medicine Bill Amount...("+total.getText()+")..");}
    }//GEN-LAST:event_payActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
        String BillNo=bid.getText();
        String Total=total.getText();
        String Paid=paid.getText();
        String Balance=balance.getText();
        if(!Total.isEmpty() && !Paid.isEmpty() && !Balance.isEmpty()){
            try(Connection c=JDBC.con();PreparedStatement ps=c.prepareStatement("sp_bill_insert ?,?,?,?,?,?,?,?,?")){
                 for(int i=0;i<billtable.getRowCount();i++){
                     ps.setString(1,BillNo);
                     ps.setString(2,billtable.getValueAt(i,1).toString());
                     ps.setString(3,billtable.getValueAt(i,2).toString());
                     ps.setString(4,billtable.getValueAt(i,3).toString());
                     ps.setString(5,Total);
                     ps.setString(6,Paid);
                     ps.setString(7,Balance);
                     ps.setString(8,date.getText());
                     ps.setString(9,time.getText());
                     ps.addBatch();
                 }
                 ps.executeBatch();
                 JOptionPane.showMessageDialog(this,"Bill Is Saved For Store Area.....");
             }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
        }else{JOptionPane.showMessageDialog(this,"Please Paid For Bill");}       
    }//GEN-LAST:event_billActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        String BillNo=bid.getText();
        String Date =date.getText();
        String CompanyName="ANG PHARMACY CENTRE";
        String Space=" ";
        String Gtot=total.getText();
        String Paid=paid.getText();
        String Balance=balance.getText();
        String HeaderText=CompanyName+Space+"BILL NO : "+BillNo+Space+Date;
        String FooterText="Grand Total : "+Gtot+Space+"Paid :"+Paid+Space+"Balance :"+Balance;
        if(!Gtot.isEmpty() && !Paid.isEmpty() && !Balance.isEmpty()){
        try {
            boolean complete=billtable.print(JTable.PrintMode.FIT_WIDTH,
                    new MessageFormat(HeaderText),
                    new MessageFormat(FooterText));
            if(complete){
                   JOptionPane.showMessageDialog(this,"Printing complete ..","Print",JOptionPane.INFORMATION_MESSAGE);
            }else{JOptionPane.showMessageDialog(this,"Printing Failed ..","Print",JOptionPane.INFORMATION_MESSAGE);}
        } catch (PrinterException ex) {
            Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{JOptionPane.showMessageDialog(this,"GRANDTOTAL, PAID, BALANCE FIELDS ARE REQUIRED FOR PDF GENEARTE..");}
    }//GEN-LAST:event_printActionPerformed

    private void billdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billdetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Billdetails().setVisible(true);
    }//GEN-LAST:event_billdetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField bid;
    private javax.swing.JButton bill;
    private javax.swing.JButton billdetails;
    private javax.swing.JTable billtable;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JLabel date;
    private javax.swing.JButton go;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField paid;
    private javax.swing.JButton pay;
    private javax.swing.JTextField price;
    private javax.swing.JButton print;
    private javax.swing.JTextField quan;
    private javax.swing.JButton remove;
    private javax.swing.JButton reset;
    private javax.swing.JTextField stock;
    private javax.swing.JTable table;
    private javax.swing.JLabel time;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
