/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_application;

import DB.JDBC;
import java.sql.*;
import javax.swing.*;
import Regex.CHECK;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kanniyappan.s
 */
public class Company extends javax.swing.JFrame {

    /**
     * Creates new form Company
     */
    public Company() {
        initComponents();
        tab();
        increment();
    }
private boolean isNumber(String Number){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select count(*) from company where phonenumber=?")){
              pst.setString(1,Number);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){
                 return rs.getInt(1)>0;
              }
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          return false;
    }
    private boolean isNumberOwner(String Id,String Number){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select count(*) from company where company_id=? and phonenumber=?")){
              pst.setString(1,Id);
              pst.setString(2,Number);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){
                 return rs.getInt(1)>0;
              }
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          return false;
    }
     private boolean isEmail(String Email){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select count(*) from company where email=?")){
              pst.setString(1,Email);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){
                 return rs.getInt(1)>0;
              }
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          return false;
    }
     private boolean isEmailOwner(String Id,String Email){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select count(*) from company where company_id=? and email=?")){
              pst.setString(1,Id);
              pst.setString(2,Email);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){
                 return rs.getInt(1)>0;
              }
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          return false;
    }
     public void increment(){
       try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select max(company_id) from company")){
           ResultSet rs=pst.executeQuery();
           rs.next();
           String Mid=rs.getString(1);
            if(Mid==null){
             cid.setText("CP001");
            }
            else{
            int id=Integer.parseInt(Mid.substring(2));
            id++;
            cid.setText(String.format("CP%03d",id));
            }
       }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
    }
     public void tab(){
       try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_company_getall")){
           ResultSet rs=pst.executeQuery();
           DefaultTableModel m=(DefaultTableModel)table.getModel();
           m.setRowCount(0);
           while(rs.next()){
             m.addRow(new Object[]{rs.getString("company_id"),rs.getString("companyname"),rs.getString("address"),
             rs.getString("phonenumber"),rs.getString("email"),rs.getString("experience")});
           }
       }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
     }
     public void clear(){
       cid.setText("");
       cname.setText("");
       caddress.setText("");
       phonenumber.setText("");
       emailid.setText("");
       experience.setText("");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        caddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        experience = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        companyname = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPANY");
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 121, 242));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Company-Mini.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("COMPANY MANIPULATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COMPANY ID", "COMPANY NAME", "COMPANY ADDRESS", "PHONE NUMBER", "EMAIL ID", "EXPERIENCE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(40);
        table.setSelectionBackground(new java.awt.Color(51, 0, 51));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 434, 976, 195));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("COMPNAY ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 128, 220, 37));

        cid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 128, 226, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("COMPANY NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 183, 220, 37));

        cname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 183, 226, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("COMPANY ADDRESS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 238, 220, 37));

        caddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 238, 226, 37));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("PHONE NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 128, 220, 37));

        phonenumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phonenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenumberFocusLost(evt);
            }
        });
        getContentPane().add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 128, 226, 37));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("EMAIL ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 183, 220, 37));

        emailid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailidFocusLost(evt);
            }
        });
        getContentPane().add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 183, 226, 37));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("EXPERIENCE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 238, 220, 37));

        experience.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 238, 226, 37));

        add.setBackground(new java.awt.Color(255, 207, 93));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 306, 176, 38));

        edit.setBackground(new java.awt.Color(102, 204, 255));
        edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 0));
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 306, 220, 38));

        delete.setBackground(new java.awt.Color(102, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 306, 224, 38));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("COMPANY NAME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 387, 165, 40));

        companyname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(companyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 387, 233, 40));

        search.setBackground(new java.awt.Color(0, 153, 51));
        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 388, 110, 40));

        clear.setBackground(new java.awt.Color(255, 255, 153));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.setToolTipText("");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 635, 175, 39));

        close.setBackground(new java.awt.Color(51, 0, 0));
        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 635, 174, 39));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String Id=cid.getText();
        int a=JOptionPane.showConfirmDialog(this,"DO YOU WANT DELETE THIS COMPANY ?","SELECT",JOptionPane.YES_NO_OPTION);
        if(!Id.isEmpty()){
            if(a==0){
               try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_company_delete ?")){
                   pst.setString(1,Id);
                   pst.executeUpdate();
                   JOptionPane.showMessageDialog(this,"This Company Is Deleted...");
                   tab();
                   clear();
                   increment();
               }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
            }            
        }else{JOptionPane.showMessageDialog(this,"Please Select Company Id");}
    }//GEN-LAST:event_deleteActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        edit.setEnabled(false);
        delete.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Company().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String Id=cid.getText();
        String Name=cname.getText();
        String Address=caddress.getText();
        String Number=phonenumber.getText();
        String Email=emailid.getText();
        String Exp=experience.getText();
        if(isNumber(Number)){
          JOptionPane.showMessageDialog(this,"This Number Already Exits.....");
          return;
        }
        if(isEmail(Email)){
          JOptionPane.showMessageDialog(this,"This Email Id Already Exits.....");
          return;
        }
        if(!Id.isEmpty() && !Name.isEmpty() && !Address.isEmpty() && !Number.isEmpty() && !Email.isEmpty() && !Exp.isEmpty()){
          try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_company_insert ?,?,?,?,?,?")){
               pst.setString(1,Id);
               pst.setString(2,Name);
               pst.setString(3,Address);
               pst.setString(4,Number);
               pst.setString(5,Email);
               pst.setString(6,Exp);
               int a=pst.executeUpdate();
               if(a>0){
                  JOptionPane.showMessageDialog(this,"Company Details Added...");
                  tab();
                  clear();
                  increment();
              }else{JOptionPane.showMessageDialog(this,"Failed Company Details Add Process...");}
          }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
        }else{JOptionPane.showMessageDialog(this,"Please Enter All The Fields.....");}
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
         String Id=cid.getText();
        String Name=cname.getText();
        String Address=caddress.getText();
        String Number=phonenumber.getText();
        String Email=emailid.getText();
        String Exp=experience.getText();
         if(!isNumberOwner(Id,Number)&& isNumber(Number)){
              JOptionPane.showMessageDialog(this,"This Number Already Exits. Please Enter Another Phone Number");
              return;
           }
           if(!isEmailOwner(Id,Email)&& isEmail(Email)){
              JOptionPane.showMessageDialog(this,"This Email Id Already Exits. Please Enter Another Email Id");
              return;
           }
          if(!Id.isEmpty()){
              try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_company_update ?,?,?,?,?,?")){
                pst.setString(1,Id);
               pst.setString(2,Name);
               pst.setString(3,Address);
               pst.setString(4,Number);
               pst.setString(5,Email);
               pst.setString(6,Exp);
               int a=pst.executeUpdate();
               if(a>0){
                  JOptionPane.showMessageDialog(this,"Company Details Edited...");
                  tab();
                  clear();
                  increment();
              }else{JOptionPane.showMessageDialog(this,"Failed Company Details Edit Process...");}
              }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
          }else{JOptionPane.showMessageDialog(this,"Please Select Company Id");}
    }//GEN-LAST:event_editActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String Name=companyname.getText();
        if(!Name.isEmpty()){
            try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_company_getById ?")){
                pst.setString(1,Name);
                ResultSet rs=pst.executeQuery();
                DefaultTableModel m=(DefaultTableModel)table.getModel();
                m.setRowCount(0);
                if(rs.next()){
                    m.addRow(new Object[]{rs.getString("company_id"),rs.getString("companyname"),rs.getString("Address"),
                    rs.getString("phonenumber"),rs.getString("email"),rs.getString("experience")});
                }
            }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
        }else{JOptionPane.showMessageDialog(this,"Please Enter Compnay Name");}
    }//GEN-LAST:event_searchActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index=table.getSelectedRow();
        TableModel m=table.getModel();
        cid.setText(m.getValueAt(index,0).toString());
        cname.setText(m.getValueAt(index,1).toString());
        caddress.setText(m.getValueAt(index,2).toString());
        phonenumber.setText(m.getValueAt(index,3).toString());
        emailid.setText(m.getValueAt(index,4).toString());
        experience.setText(m.getValueAt(index,5).toString());
        add.setEnabled(false);
        edit.setEnabled(true);
        delete.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void phonenumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumberFocusLost
        // TODO add your handling code here:
        String Number=phonenumber.getText();
        if(!Regex.CHECK.isValidPhone(Number)){
             JOptionPane.showMessageDialog(this,"Please Enter Valid Phone Number...");
             return;
        }
    }//GEN-LAST:event_phonenumberFocusLost

    private void emailidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailidFocusLost
        // TODO add your handling code here:
        String Email=emailid.getText();
        if(!Regex.CHECK.isValidEmail(Email)){
          JOptionPane.showMessageDialog(this,"Please Enter Valid Email Id");
          return;
        }
    }//GEN-LAST:event_emailidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField caddress;
    private javax.swing.JTextField cid;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField companyname;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField emailid;
    private javax.swing.JTextField experience;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JButton search;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
