/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_application;

/**
 *
 * @author kanniyappan.s
 */
import javax.swing.*;
import java.sql.*;
import DB.JDBC;
import Regex.CHECK;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Date;
public class MedicineForm extends javax.swing.JFrame {

    /**
     * Creates new form MedicineForm
     */
    public MedicineForm() {
        initComponents();
        tab();
        companyname();
        increment();
    }
     public void increment(){
       try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select max(id) from medicine")){
           ResultSet rs=pst.executeQuery();
           rs.next();
           String Mid=rs.getString(1);
            if(Mid==null){
             mid.setText("ME001");
            }
            else{
            int Cid=Integer.parseInt(Mid.substring(2));
            Cid++;
            mid.setText(String.format("ME%03d",Cid));
            }
         }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
    }
    public void tab(){
    try(Connection c=JDBC.con();PreparedStatement st=c.prepareStatement("sp_medicine_getall")){
        ResultSet rs=st.executeQuery();
        DefaultTableModel m=(DefaultTableModel)table.getModel();
        m.setRowCount(0);
        while(rs.next()){
          m.addRow(new Object[]{rs.getString("id"),rs.getString("name"),rs.getInt("quantity"),rs.getString("price"),rs.getString("manufacturedate"),rs.getString("expiredate"),rs.getString(("companyname"))});
        }
    }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
    }
    public void companyname(){
      try(Connection c=JDBC.con();PreparedStatement st=c.prepareStatement("sp_company_getall")){
          ResultSet rs=st.executeQuery();
          companyname.removeAllItems();
          companyname.addItem("SELECT COMPANYNAME");
          while(rs.next()){
            String Name=rs.getString("companyname");
               companyname.addItem(Name);
          }
      }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
    }
    public void clear(){
      mid.setText("");
      mname.setText("");
      mstock.setText("");
      mprice.setText("");
      mdate.setDate(null);
      edate.setDate(null);
      companyname.setSelectedItem("SELECT COMPANYNAME");
    }
    SimpleDateFormat dt=new SimpleDateFormat("yyyy-MM-dd");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        clear = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mstock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mdate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        edate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        companyname = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        medicinename = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MEDICINE FORM");
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Medicine-Mini.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEDICINE FORM MANIPULATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINE ID", "MEDICINE NAME", "STOCK", "PRICE", "MANUFACTURE DATE", "EXPIRE DATE", "COMPANY NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(40);
        table.setSelectionBackground(new java.awt.Color(51, 0, 0));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 437, 988, 206));

        clear.setBackground(new java.awt.Color(153, 153, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 649, 170, 33));

        close.setBackground(new java.awt.Color(102, 0, 0));
        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 649, 170, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("MEDICINE ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 106, 161, 41));

        mid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 106, 249, 41));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("MEDICINE NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 165, 161, 41));

        mname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 165, 249, 41));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("STOCK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 227, 161, 41));

        mstock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 227, 249, 41));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("PRICE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 287, 161, 41));

        mprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 287, 249, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("MANUFACTUTE DATE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 106, 205, 41));

        mdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 106, 277, 41));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("EXPIRE DATE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 165, 205, 41));

        edate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(edate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 165, 277, 43));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("COMPANY NAME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 224, 205, 41));

        companyname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        companyname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(companyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 226, 277, 43));

        add.setBackground(new java.awt.Color(0, 0, 51));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 340, 226, 38));

        edit.setBackground(new java.awt.Color(255, 255, 51));
        edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(51, 0, 51));
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 340, 233, 38));

        delete.setBackground(new java.awt.Color(102, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 340, 226, 38));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("MEDICINE NAME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 397, 163, 34));

        medicinename.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(medicinename, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 396, 314, 35));

        search.setBackground(new java.awt.Color(0, 102, 51));
        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 396, 131, 35));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MedicineForm().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index=table.getSelectedRow();
        TableModel m=table.getModel();
        mid.setText(m.getValueAt(index, 0).toString());
        mname.setText(m.getValueAt(index,1).toString());
        mstock.setText(m.getValueAt(index,2).toString());
        mprice.setText(m.getValueAt(index,3).toString());
        try {
            mdate.setDate(dt.parse((String)m.getValueAt(index,4)));
            edate.setDate(dt.parse((String)m.getValueAt(index,5)));
        } catch (ParseException ex) {
            Logger.getLogger(MedicineForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        companyname.setSelectedItem(m.getValueAt(index,6).toString());
        add.setEnabled(false);
        edit.setEnabled(true);
        delete.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
       String Id=mid.getText();
       String Name=mname.getText();
       String Stock=mstock.getText();
       String Price=mprice.getText();
       String CompanyName=(String)companyname.getSelectedItem();
       String Text="SELECT COMPANYNAME";
     if(!Id.isEmpty()&& !Name.isEmpty()&&!Stock.isEmpty()&& !Price.isEmpty()){
         if(mdate.getDate()==null){
            JOptionPane.showMessageDialog(this,"Please Select Manufacture Date...");
            return;
         }
         if(edate.getDate()==null){
            JOptionPane.showMessageDialog(this,"Please Select Expire Date...");
            return;
         }
          if(CompanyName.equals(Text)){
           JOptionPane.showMessageDialog(this,"Please Select CompanyName.....");
           return;
         }
         
         try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_medicine_insert ?,?,?,?,?,?,?")){
         int Quan=Integer.parseInt(Stock);
         String Mdate=dt.format(mdate.getDate());
         String Edate=dt.format(edate.getDate());
         Date d1=dt.parse((String)Mdate);
         Date d2=dt.parse((String)Edate);
         if(d1.before(d2)){
             pst.setString(1,Id);
             pst.setString(2,Name);
             pst.setInt(3, Quan);
             pst.setString(4,Price);
             pst.setString(5,Mdate);
             pst.setString(6,Edate);
             pst.setString(7,CompanyName);
             int a=pst.executeUpdate();
             if(a>0){
                JOptionPane.showMessageDialog(this,"Medicine Details Added.....");
                clear();
                tab();
                increment();
             }
             else{
               JOptionPane.showMessageDialog(this,"Failed Medicine Details Add Process...");
             }
         }else{JOptionPane.showMessageDialog(this,"Please Select Correct Manufacture Date And Expire Date.....");}
        }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
       }else{JOptionPane.showMessageDialog(this,"Please Enter All Fields.....");}
       
    }//GEN-LAST:event_addActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        edit.setEnabled(false);
        delete.setEnabled(false);
        mid.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
       String Id=mid.getText();
       String Name=mname.getText();
       String Stock=mstock.getText();
       String Price=mprice.getText();
       String CompanyName=(String)companyname.getSelectedItem();
    if(!Id.isEmpty()){
         try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_medicine_update ?,?,?,?,?,?,?")){
         int Quan=Integer.parseInt(Stock);
         String Mdate=dt.format(mdate.getDate());
         String Edate=dt.format(edate.getDate());
         Date d1=dt.parse((String)Mdate);
         Date d2=dt.parse((String)Edate);
         if(d1.before(d2)){
             pst.setString(1,Id);
             pst.setString(2,Name);
             pst.setInt(3, Quan);
             pst.setString(4,Price);
             pst.setString(5,Mdate);
             pst.setString(6,Edate);
             pst.setString(7,CompanyName);
             int a=pst.executeUpdate();
             if(a>0){
                JOptionPane.showMessageDialog(this,"Medicine Details Edited.....");
                clear();
                tab();
                increment();
             }
             else{
               JOptionPane.showMessageDialog(this,"Failed Medicine Details Edit Process...");
             }
         }else{JOptionPane.showMessageDialog(this,"Please Select Correct Manufacture Date And Expire Date.....");}
        }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
       }else{JOptionPane.showMessageDialog(this,"Please Select Medicine Id.....");}       
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String Id=mid.getText();
        int a=JOptionPane.showConfirmDialog(this,"DO YOU WANT DELETE THIS MEDICINE ID ?","SELECT",JOptionPane.YES_NO_OPTION);
        if(!Id.isEmpty()){
            if(a==0){
              try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("sp_medicine_delete ?")){
                  pst.setString(1,Id);
                  pst.executeUpdate();
                  clear();
                  tab();
                  increment();
                  JOptionPane.showMessageDialog(this,"This Medicine Id Was Deleted....");
               }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
            }
        }else{JOptionPane.showMessageDialog(this,"Please Select Medicine Id...");}
    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String Name=medicinename.getText();
        if(!Name.isEmpty()){
            try(Connection c=JDBC.con();PreparedStatement pst=c.prepareStatement("select * from medicine where name=?")){
                pst.setString(1,Name);
                ResultSet rs=pst.executeQuery();
                DefaultTableModel m=(DefaultTableModel)table.getModel();
                m.setRowCount(0);
                if(rs.next()){
                  m.addRow(new Object[]{rs.getString("id"),rs.getString("name"),rs.getString("quantity"),rs.getString("price"),rs.getString("manufacturedate"),rs.getString("expiredate"),rs.getString("companyname")});
                }
            }catch(Exception e){JOptionPane.showMessageDialog(this,e);}
        }else{JOptionPane.showMessageDialog(this,"Please Enter Medicine Name.....");}
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> companyname;
    private javax.swing.JButton delete;
    private com.toedter.calendar.JDateChooser edate;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser mdate;
    private javax.swing.JTextField medicinename;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mprice;
    private javax.swing.JTextField mstock;
    private javax.swing.JButton search;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
